const menus = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 151.99,
    img: "https://react-projects-5-menu.netlify.app/images/item-1.jpeg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 131.99,
    img: "https://react-projects-5-menu.netlify.app/images/item-2.jpeg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 61.99,
    img: "https://react-projects-5-menu.netlify.app/images/item-3.jpeg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 201.99,
    img: "https://react-projects-5-menu.netlify.app/images/item-4.jpeg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 221.99,
    img: "https://react-projects-5-menu.netlify.app/images/item-5.jpeg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 181.99,
    img: "https://react-projects-5-menu.netlify.app/images/item-6.jpeg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 81.99,
    img: "https://react-projects-5-menu.netlify.app/images/item-7.jpeg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 121.99,
    img: "https://react-projects-5-menu.netlify.app/images/item-8.jpeg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 161.99,
    img: "https://react-projects-5-menu.netlify.app/images/item-9.jpeg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    count: 0,
    total: 0,
  },
];

export default menus;
